### ISSUE TITLE
Total Economy /baltop Issue

### ISSUE THREAD

**Issue by yepidoodles** [Arckenver/Nations#107]
I was wondering if you might be able to do something about this.

https://gyazo.com/0f3abeb767a546a7609b554e60ceb98b

http://www.codesend.com/view/1df3d0670765e6b368b5c4a886a7445b/

**Comment by TheoKah** [comment]
What economy plugin are you using?

There are 2 kind of accounts handled by the sponge API: player's account and virtual accounts.

/baltop should only list players account so I don't know why yours is trying to access virtual ones.

Edit: just re-read your title, you are using Total Economy, I'll check what they do

**Comment by TheoKah** [comment]
This is because Total Economy do not handle virtual accounts correctly.

https://github.com/Erigitic/TotalEconomy/issues/126

You can either wait for them to add support for virtual accounts or switch to another economy plugin.
I'm using EconomyLite on my servers and it is working nicely:
https://forums.spongepowered.org/t/moneybag-economylite-v2-10-0-api-5-0-6-0/7045

**Comment by yepidoodles** [comment]
I don't think my 300 current players would appricate their accounts being reset :P I'll wait, thanks for the info.
