### ISSUE TITLE
[Request] Zones and Shop Signs

### ISSUE THREAD

**Issue by yepidoodles** [Arckenver/Nations#109]
So I set up zones to sell as shops at my spawn but people can not interact with the signs unless interact is turned on, which also allows access to the chests (So people could just steal the items instead). 

Please could you fix this asap?

Perhaps add a sign flag

**Comment by TheoKah** [comment]
What signs are you talking about?
What mod are you using for the shop?

**Comment by yepidoodles** [comment]
https://forums.spongepowered.org/t/player-shops-v1-0-0-buy-and-sell-items-to-and-from-other-players/14373

https://gyazo.com/cd8c925294dd299d46afd75937a00a66

You right click the sign to sell/buy items, but the interact flag blocks it

**Comment by TheoKah** [comment]
Ok,
This would be for the plugin author to use different event levels in that case.
That's what I did for my shop plugin ( https://ore.spongepowered.org/Carrot/CarrotShop )

I cannot efficiently protect those shops with nation, because I would need a way to make the distinction between a normal sign and a shop sign (using the 1st line of text is NOT a good way of doing this because this might an unlinked shop, or even a real shop that has been edited by a mod afterwards...)

**Comment by yepidoodles** [comment]
Oh my god, I've been looking for a plugin that's like SignShop, is it just as compatible with mods as the original plugin? It seems to work just like SignShop, any important changes? I saw you added Trading, that's very cool.

**Comment by TheoKah** [comment]
You can sell modded items with it.
Restriction for now is the chest needs to be loaded (unlike the bukkit one where you could use a chest un an unloaded area)

The mod is working with Nations.

Report any bug/suggestion on this page if you plan on using it: https://github.com/TheoKah/CarrotShop/issues

**Comment by yepidoodles** [comment]
Many thanks.
