### ISSUE TITLE
[Suggestion] Whitelist for never-to-be-check blocks in nations

### ISSUE THREAD

**Issue by CarlTornberg** [Arckenver/Nations#118]
Say if you want to place eastereggs in the spawn and give players the ability to take it, you can set that block as whitelisted.

Ex: Player is in the spawn area, admin manually places diamond och iron blocks for players to find. Have a 
whitelist: {
    "minecraft:diamond_block"
    "minecraft:iron_block"
}
in the config file.

**Comment by TheoKah** [comment]
I'll add a whitelist in v2.6

**Comment by HeberonYT** [comment]
Hi. When will the whitelist arrive?

**Comment by HeberonYT** [comment]
With all due respect, it is not possible that it takes more than 6 months to add this elemental feature, not to mention the myriad extra reports that I have also created and still do not solve. Currently you are in version 2.8 and none of the above has been included, mentioned since version 2.6 that would be added and only postponed the publication.
It is better to abandon a project, than to promise in vain.
#161 - How is it possible that this is still failing? This is supposed to be something elementary that protects the mod :laughing:
#144 - #143 - #150

**Comment by TheoKah** [comment]
1. As wierd as it can be, I have a job and family to deal with. Minecraft is a game.
2. Version 2.7 and 2.8 are just bugfix and api ports, nothing really new since 2.6
3. The project is opensource and you are free to contribute.
4. Do not be a dick

**Comment by HeberonYT** [comment]
I really want you to be more successful with your family, because of the projects to which you contribute better we do not talk.
However, if versions 2.7 and 2.8 are only bugfix, what are you contributing to? He imagined they contained things of interest.

**Comment by TheoKah** [comment]
Looks like you missed point 4 :/

**Comment by Arckenver** [comment]
Nations has been completely re-written in Kotlin since [version v3.0](https://github.com/Arckenver/Nations/releases/tag/v3.0), I'm therefore closing all issues opened prior to `v3.0`.

Please, feel free to re-create a new issue if the topic is still relevant.
