### ISSUE TITLE
Buying zones when not in a Nation

### ISSUE THREAD

**Issue by yepidoodles** [Arckenver/Nations#126]
Currently you can not buy a zone unless you're already in a Nation. I suggest that when someone buys a zone when not in a Nation, they automaticly join that Nation, or allow them to buy the zone when not in a Nation.

**Comment by TheoKah** [comment]
If you set a zone as 'public' one should be able to buy it even if not in the same nation.
(Make sure it is up for sale)

**Comment by yepidoodles** [comment]
It's when the player is in **no Nation at all**

**Comment by yepidoodles** [comment]
http://www.codesend.com/view/ab067a36218bcd6731e8c1ad7812ceb6/

**Comment by TheoKah** [comment]
I'll check that. Thank you :)

**Comment by yepidoodles** [comment]
Perhaps add a config option for my suggestion about automaticly adding the player to the nation when they buy a zone if they aren't in one already, or even a flag for it.

**Comment by TheoKah** [comment]
Sorry for late answer about this one.

This was the intended behaviour but the conditions were not in the correct order.
In v2.5, you should be able to buy a zone if:
zone is in admin nation OR zone is marked "public" OR you belong to the same nation

I wont add the auto-join nation thing because a nation can be set as "open" already so anyone can join it
