### ISSUE TITLE
Suggestion - Option to allow people to join multiple Nations

### ISSUE THREAD

**Issue by yepidoodles** [Arckenver/Nations#85]
As the title says, it would be great to have the option to allow people to join several Nations.

- Alice

**Comment by TheoKah** [comment]
What would be the point of that?

While this wont be difficult having a "main" nation along other "secondary" ones, I see little interest.

If this is just because you want to give build/interact permission to specific players that are not in the nation without giving perms to "outsiders", we can do something with the zones. Like having a zone flag that would allow outsiders to buy it...

**Comment by yepidoodles** [comment]
In my 1.7.10 servers we used MyTown2, in which my players begged me to turn on multiple towns. People want to be able to play with their friends without working with them, without sharing Nations. I can get everyone who wants this to post here if you want.

**Comment by turtledude01** [comment]
I actually like this idea as well, would add an interesting aspect to the game.

**Comment by tbone1110** [comment]
I believe this option should exist too.

**Comment by TheoKah** [comment]
I have mixed feelings about this one:

Having more than 1 nation per player can be a little confusing when it comes to handling permissions on the nation.

However I see why you want it: Two friends that each own their nation might want to be able to share a plot.

Best idea I have would be the following. Use the "open" flag on zone and make it so outsiders can buy a zone if the flag is set to "open"
This way, player A can buy a zone in player B's nation and get perm there.
Would this be good enough ?

**Comment by yepidoodles** [comment]
I believe this would be sufficient.

**Comment by TheoKah** [comment]
Feature is now available in [version 2.3](https://github.com/Arckenver/Nations/releases/tag/v2.3)
