### ISSUE TITLE
Suggestion: Container Selection

### ISSUE THREAD

**Issue by Shane1199** [Arckenver/Nations#94]
For quick reference, I believe this was partially mentioned in #24 , #30 and #82  

My suggestion is to allow, either the config or the players to choose what items to allow to be used. Chests, Doors, and Gates are some examples. One bug, mentioned in the latter issue reference, is that players can break item frames and remove/add items from/to them.

The reason for my suggestion, is that my server wants to allow some Pixelmon-mod items at spawn to be usable, such as the PC and the vanilla Enderchest. But we also had item frames displaying the blocks in the in-game shop and players could steal the items and the item frames. So if in-game I could choose the Spawn Nation to block item frames from being "used" then I'd be good. I realize this may be a tough suggestion or take some recode to do, but it's something I need and likely others do to.

**Comment by TheoKah** [comment]
Next release will protect entities (including item frames)
I made it so itemframes interactions are protected using the "build" rules instead of the "interaction" rule.

This mean you will be able to set build permission to false and interaction to true in this area.
This would allow access to PC and enderchest, but not item frames, even if players 'interact' with it.
